### ISSUE TITLE
Can I use the environment released in the original airsim in UrdfSim ? 

### ISSUE THREAD

**Issue by guldamkwak3114** [mitchellspryn/UrdfSim#35]
There are a number of Arisim environment released 

https://github.com/microsoft/AirSim/releases

Can I use them in URDFsim so that my robots drive in one of the environments there ?

**Comment by mitchellspryn** [comment]
If you can get access to the assets, sure. You'd just rebuild the project using the urdfsim plugin instead of the airsim one. 

However, if you just have their pre-built binaries, then no. That's more of a legal question than a technical one (as for at least some of the assets, they've been purchased from the Unreal store, so they can't just give them away for free).
